### ISSUE TITLE
Rendering the bare website from this repo instead of running it from the loklak_server

### ISSUE THREAD

**Issue by sudheesh001** [loklak/loklak.github.io#2]
The `html` folder in the `loklak_server` repository which hosts the landing website could also be put up here statically while using the search capability to fire an Ajax query to the API instead and maintaining the existing functionality.

If this is the reason this repository has been made, I'd be more than happy to send the patch and get the basic site refactored from loklak_server repository to this repository.

Guidance please: @Orbiter , @mariobehling

**Comment by Orbiter** [comment]
loklak won't change and the html has to stay inside to enable everybody to have an exact clone of loklak.org and keep independence from hostting, including github.
