### ISSUE TITLE
Need of favicon

### ISSUE THREAD

**Issue by meets2tarun** [loklak/loklak.github.io#5]
There must be fevicon on [website](loklak.org) of loklak.

**Comment by yukiisbored** [comment]
This repository **only** purpose is to forward to loklak.org when someone is using the old url. It does not require a fix nor any type of improvements, etc because it works and you can see it here

**Comment by yukiisbored** [comment]
Your issue should be on [loklak_server](https://GitHub.com/loklak/loklak_server)
