### ISSUE TITLE
Clone the Git Repo Tab not working

### ISSUE THREAD

**Issue by meets2tarun** [loklak/loklak.github.io#6]
There is a tab which written clone the git repo tab:
Download, install and extend is redirecting to NOT FOUND 404 page. [page](http://loklak.org/download.html)

**Comment by yukiisbored** [comment]
This repository **only** purpose is to forward to loklak.org when someone is using the old url. It does not require a fix nor any type of improvements, etc because it works and you can see it [here](loklak.github.io)

**Comment by yukiisbored** [comment]
Also, your issue should be on [loklak_server](github.com/loklak/loklak_server)
